### PR TITLE
flatten file organization to reflect entity folder

### PR DESCRIPTION
**Pull request by brikou**
- some tweaks

### CODE REVIEW

**Comment by stof** [comment]
Why moving the types ? Having them in the `Form\Type` subnamespace is the convention on which we agreed in the doc (using `Form\Model` for form-specific non-persistent models, etc...)

**Comment by brikou** [comment]
@stof I didn't know it was in doc... I probably should revert it then... And what do you think about moving OrderFactoryType class to Factory Folder in order to reflect the structure found in Entity/Factory folder?

**Comment by stof** [comment]
I don't think it is needed here.

**Comment by brikou** [comment]
It seems that in sf standard edition (...DemoBundle...) ContactType.php is located at the root folder which seems to be the right place... can you point me to the doc where this convention is used?

**Comment by stof** [comment]
The standard edition has not been updated after @weaverryan and I suggested a convention: https://github.com/symfony/symfony-docs/pull/496

**Comment by brikou** [comment]
ok so refering to this i should move Form/Factory to Form/Model and keep Form/Type

**Pull request closed without merging**
